theme: jekyll-theme-minimal
title: Avoin data opetuskäyttöön - näillä ohjeilla alkuun!
url: "https://avoin-data-opas.github.io"
defaults:
    -
     scope:
         path: "en"
     values:
         layout: default_en
         lang: en
         baseurl: "en/"
    -
     scope:
         path: ""
     values:
         lang: fi
         baseurl: ""
         layout: default
